name: SonarQube Scan

on:
  push:
    branches:
      - main  # Ajustar si la rama principal tiene otro nombre

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Clonar todo el historial mejora la relevancia del análisis

      # Si tu proyecto necesita Java para compilar (p.ej. Maven/Gradle), añade:
      #- name: Set up JDK 11
      #  uses: actions/setup-java@v3
      #  with:
      #    java-version: '11'

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN:    ${{ secrets.SONAR_TOKEN }}
        # Si no usas Maven/Gradle, el escáner detectará automáticamente
        # tu setup y analizará el código según sonar-project.properties
